// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: reset.sql

package database

import (
	"context"
)

const resetTokens = `-- name: ResetTokens :exec
DELETE FROM refresh_tokens
`

func (q *Queries) ResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetTokens)
	return err
}

const resetUsers = `-- name: ResetUsers :exec
DELETE FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}
